### ISSUE TITLE
Error inside Timer example

### ISSUE THREAD

**Issue by equinusocio** [flintjs/examples#2]
There is an error inside [Button.js on line 5 and 17](https://github.com/flintjs/examples/blob/master/timer/button.js#L5) . Double `border` key declaration.

**Comment by ncammarata** [comment]
Thanks for letting us know. Our new compiler-time style checks caught it. So cool!

![image](https://cloud.githubusercontent.com/assets/204989/12311082/9316f84e-ba09-11e5-8959-39e527e8b1cc.png)

**Comment by ncammarata** [comment]
fixed in 245c5e27df3cc376075917ccaf1870a9e2b75de5 and updated to new experimental props syntax
